name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gnome-version: [48, 49, 50]
    container:
       image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-${{ matrix.gnome-version }}
       options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        with:
          version: 0.17.0-dev
      - name: Run tests
        run: |
          # For unknown reasons, the build does not seem to be able to create
          # this directory itself (AccessDenied), but works if it's created in
          # advance.
          mkdir -p .zig-cache

          .github/workflows/flatpak-run.sh ${{ matrix.gnome-version }} <<EOF
          zig build test
          EOF
      - name: Generate bindings
        run: |
          # For unknown reasons, the build does not seem to be able to create
          # this directory itself (AccessDenied), but works if it's created in
          # advance.
          mkdir -p zig-out/bindings/build

          .github/workflows/flatpak-run.sh ${{ matrix.gnome-version }} <<EOF
          zig build codegen -Dgir-profile=gnome${{ matrix.gnome-version }}
          EOF
      - name: Test bindings
        run: |
          # Some tests do not work without a display
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99

          .github/workflows/flatpak-run.sh ${{ matrix.gnome-version }} <<EOF
          cd zig-out/bindings
          zig build test
          EOF
      - name: Build example
        run: |
          .github/workflows/flatpak-run.sh ${{ matrix.gnome-version }} <<EOF
          cd example
          zig build
          EOF
      - name: Configure GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' && matrix.gnome-version == 50 }}
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Build docs
        if: ${{ github.ref == 'refs/heads/main' && matrix.gnome-version == 50 }}
        run: |
          .github/workflows/flatpak-run.sh ${{ matrix.gnome-version }} <<EOF
          cd zig-out/bindings
          zig build docs -Dautodoc-fork
          EOF
      - name: Upload docs artifact
        if: ${{ github.ref == 'refs/heads/main' && matrix.gnome-version == 50 }}
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: zig-out/bindings/zig-out/docs

  publish-docs:
    needs: [test]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
